using Library;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace Guideviewer
{
	class CheckBoxViewModel
	{
		public ObservableCollection<CheckBoxModel> AllCheckboxes { get; set; }

        public List<Tuple<string, string>> CheckBoxTupleInfoMqc = new List<Tuple<string, string>>
        {
            //Miniquests
            new Tuple<string, string>( "Abyssal_Reach", "The Abyss" ),
            new Tuple<string, string>( "Bar_Crawl", "Barcrawl" ),
            new Tuple<string, string>( "The_Curse_of_Zaros", "The Curse of Zaros" ),
            new Tuple<string, string>( "Desert_Slayer_Dungeon", "Desert Slayer Dungeon" ),
            new Tuple<string, string>( "Banking_History", "Banking History" ),
            new Tuple<string, string>( "Fur_%27n%27_Seek", "Fur 'n' Seek Wishlist"),
            new Tuple<string, string>( "Exploration_achievements", "Fur 'n' Seek Wishlist" ),
            new Tuple<string, string>( "Exploration_achievements", "The General's Shadow" ),
            new Tuple<string, string>( "Exploration_achievements", "Hopespear's Will" ),
            new Tuple<string, string>( "Exploration_achievements", "Hunt for Surok" ),
            new Tuple<string, string>( "Exploration_achievements", "In Memory of The Myreque" ),
            new Tuple<string, string>( "Exploration_achievements", "Knight Waves Training Grounds" ),
            new Tuple<string, string>( "Exploration_achievements", "Koschei's Troubles" ),
            new Tuple<string, string>( "From_Tiny_Acorns", "From Tiny Acorns" ),
            new Tuple<string, string>( "Lost_Her_Marbles", "Lost Her Marbles" ),
            new Tuple<string, string>( "A_Guild_of_Our_Own", "A Guild of Our Own" ),
            new Tuple<string, string>( "Exploration_achievements", "The Lair of Tarn Razorlor" ),
            new Tuple<string, string>( "Exploration_achievements", "The Lost Toys" ),
            new Tuple<string, string>( "Exploration_achievements", "Mahjarrat Memories" ),
            new Tuple<string, string>( "Exploration_achievements", "Mogre" ),
            new Tuple<string, string>( "Exploration_achievements", "Rag and Bone Man Wishlist" ),
            new Tuple<string, string>( "About_%27Kin_Time", "About 'Kin Time" ),
            new Tuple<string, string>( "Exploration_achievements", "Returning Clarence" ),
            new Tuple<string, string>( "Exploration_achievements", "Rogue Trader" ),
            new Tuple<string, string>( "Exploration_achievements", "Scabarites Notes" ),
            new Tuple<string, string>( "Exploration_achievements", "Tales of Nomad" ),
            new Tuple<string, string>( "Exploration_achievements", "Tales of the God Wars" ),
            new Tuple<string, string>( "Exploration_achievements", "Encountering TzHaar-Ga'al-Kot" ),
            new Tuple<string, string>( "Exploration_achievements", "Doric's first" ),
            new Tuple<string, string>( "Exploration_achievements", "Doric's second" ),
            new Tuple<string, string>( "Exploration_achievements", "Doric's third" ),
            new Tuple<string, string>( "Exploration_achievements", "Doric's fourth" ),
            new Tuple<string, string>( "Exploration_achievements", "Doric's fifth" ),
            new Tuple<string, string>( "Exploration_achievements", "Doric's sixth" ),
            new Tuple<string, string>( "Exploration_achievements", "Doric's seventh" ),
            new Tuple<string, string>( "Exploration_achievements", "Doric's eighth" ),
            new Tuple<string, string>( "Exploration_achievements", "Boric's first" ),
            new Tuple<string, string>( "Exploration_achievements", "Boric's second" ),
            new Tuple<string, string>( "Exploration_achievements", "Boric's third" ),
            new Tuple<string, string>( "Fred%27s_Shearings", "Sheep Shearer" ),
            new Tuple<string, string>( "Exploration_achievements", "Witch's Potion" ),
            new Tuple<string, string>( "Exploration_achievements", "Stronghold of Player Safety" ),
            new Tuple<string, string>( "Exploration_achievements", "Stronghold of Security" ),
            new Tuple<string, string>( "Exploration_achievements", "Purple Cat" ),
            new Tuple<string, string>( "Exploration_achievements", "Benedict's World Tour" ),


            //Post-Quest
            new Tuple<string, string>( "Aereck%27s_Old_Bones", "Aereck's Old Bones" ),
            new Tuple<string, string>( "Any_Odd_Chicken", "Any Odd Chicken" ),
            new Tuple<string, string>( "Exploration_achievements", "Heart of Stone - Pet" ),
            new Tuple<string, string>( "Exploration_achievements", "The Tale of the Muspah - Experience" ),
            new Tuple<string, string>( "Exploration_achievements", "River of Blood - Haemalchemy" ),
            new Tuple<string, string>( "Exploration_achievements", "Song from the Depths - Experience" ),
            new Tuple<string, string>( "Exploration_achievements", "A Shadow over Ashdale - Varies" ),
            new Tuple<string, string>( "Azacorax%27s_Rewards", "Azacorax's Rewards" ),
            new Tuple<string, string>( "Exploration_achievements", "Archmage Sedridors Chest" ),
            new Tuple<string, string>( "Blinded_by_Ramarno%27s_Teaching", "Blinded by Ramarno's Teaching" ),
            new Tuple<string, string>( "Buy_and_Sell_Some_XP", "Buy and Sell Some XP" ),
            new Tuple<string, string>( "Buying_Up_Ancient_Artefacts", "Buying Up Ancient Artefacts" ),
            new Tuple<string, string>( "Claiming_Azzanadra%27s_Heart", "Claiming Azzanadra's Heart" ),
            new Tuple<string, string>( "Claus_Is_Rising", "Claus Is Rising" ),
            new Tuple<string, string>( "Cook%27s_Delights", "Cook's Delights" ),
            new Tuple<string, string>( "Deep_and_Bloody_Experience", "Deep and Bloody Experience" ),
            new Tuple<string, string>( "Complete_Trekky", "Fires Are Mostly Harmless - Gu'Tanoth Cave" ),
            new Tuple<string, string>( "Chippy_Transport", "Chippy Transport" ),
            new Tuple<string, string>( "Advanced_Sweeping", "Advanced Sweeping - The Apprentice" ),
            new Tuple<string, string>( "Advanced_Sweeping", "Advanced Sweeping - Ali the Hag" ),
            new Tuple<string, string>( "Advanced_Sweeping", "Advanced Sweeping - Old Crone" ),
            new Tuple<string, string>( "Advanced_Sweeping", "Advanced Sweeping - Baba Yaga" ),
            new Tuple<string, string>( "Advanced_Sweeping", "Advanced Sweeping - Kardia" ),
            new Tuple<string, string>( "Around_the_World_in_Six_Ways", "Around the World in Six Ways - Crafting Guild" ),
            new Tuple<string, string>( "Around_the_World_in_Six_Ways", "Around the World in Six Ways - Lumber Yard" ),
            new Tuple<string, string>( "Around_the_World_in_Six_Ways", "Around the World in Six Ways - Castle Wars" ),
            new Tuple<string, string>( "Around_the_World_in_Six_Ways", "Around the World in Six Ways - Grand Tree" ),
            new Tuple<string, string>( "Exploration_achievements", "Mighty Fall - Coins" ),
            new Tuple<string, string>( "Exploration_achievements", "Death Plateau - Experience" ),
            new Tuple<string, string>( "Exploration_achievements", "Cabin Fever - Coins" ),
            new Tuple<string, string>( "Exploration_achievements", "You Are It - Charos' Necklace" ),
            new Tuple<string, string>( "Exploration_achievements", "Tai Bwo Wannai Trio - Experience" ),
            new Tuple<string, string>( "Exploration_achievements", "The Lost Tribe - Mining Helmet" ),
            new Tuple<string, string>( "Bloodstained_Treasure", "Bloodstained Treasure" ),
            new Tuple<string, string>( "Cower_Behind_the_Chosen_Commander", "Cower Behind the Chosen Commander" ),
            new Tuple<string, string>( "Daero_Take_This_Experience%3F", "Daero Take This Experience?" ),
            new Tuple<string, string>( "Do_No_Elite", "Do No Elite" ),
            new Tuple<string, string>( "Claiming_the_Knight%27s_Experience", "Claiming the Knight's Experience" ),
            new Tuple<string, string>( "Exploration_achievements", "Rocking Out - Coins" ),
            new Tuple<string, string>( "Epi_Logueque_Experience", "Epi logueque Experience" ),
            new Tuple<string, string>( "One_Man%27s_Junk...Is_Mine", "One Man's Junk... Is Mine" ),
            new Tuple<string, string>( "Experience_the_Fate_of_the_Gods", "Experience the Fate of the Gods" ),
            new Tuple<string, string>( "Gift_from_Sliske", "Gift from Sliske" ),
            new Tuple<string, string>( "Exploration_achievements", "The Golem - Gems" ),
            new Tuple<string, string>( "Exploration_achievements", "One Piercing Note - Cithara Experience" ),
            new Tuple<string, string>( "Exploration_achievements", "World Wakes - Firemaking" ),
            new Tuple<string, string>( "Exploration_achievements", "World Wakes - Prayer" ),
            new Tuple<string, string>( "Exploration_achievements", "The Dig Site - Abilities" ),
            new Tuple<string, string>( "Exploration_achievements", "Observatory Quest - Craft" ),
            new Tuple<string, string>( "Deadlier_Catch", "Deadler Catch" ),
            new Tuple<string, string>( "I_Presume_These_Rewards_Are_Mine,_Death%3F", "I Presume These Rewards Are Mine, Death?" ),
            new Tuple<string, string>( "Icthlarin's Little Chest", "Icthlarin's Little Chest" ),
            new Tuple<string, string>( "Exploration_achievements", "One Of A Kind - Experience" ),
            new Tuple<string, string>( "Exploration_achievements", "One Of A Kind 2 - Statue Experience" ),
            new Tuple<string, string>( "Challenge_Maria", "Challenge Maria - Challenges" ),
            new Tuple<string, string>( "Challenge_Maria", "Challenge Maria - Lamps" ),
            new Tuple<string, string>( "Circus_of_Fire", "Circus of Fire" ),

                
            //Levels
            new Tuple<string, string>( "Gunning_for_Jewellery", "Gunning for Jewellery - Ruby" ),
            new Tuple<string, string>( "Gunning_for_Jewellery", "Gunning for Jewellery - Dragonstone" ),
            new Tuple<string, string>( "Gunning_for_Jewellery", "Gunning for Jewellery - Onyx" ),
            new Tuple<string, string>( "Exploration_achievements", "50 Farming" ),
            new Tuple<string, string>( "Exploration_achievements", "50 Attack" ),
            new Tuple<string, string>( "Exploration_achievements", "50 Prayer" ),
            new Tuple<string, string>( "Exploration_achievements", "46 Farming" ),
            new Tuple<string, string>( "Exploration_achievements", "80 Defence" ),
            new Tuple<string, string>( "Exploration_achievements", "50 Prayer" ),
            new Tuple<string, string>( "Exploration_achievements", "60 Thieving" ),
            new Tuple<string, string>( "Exploration_achievements", "50 Smithing" ),
            new Tuple<string, string>( "Exploration_achievements", "50" ),
            new Tuple<string, string>( "Exploration_achievements", "100" ),
            new Tuple<string, string>( "Exploration_achievements", "150" ),
            new Tuple<string, string>( "Exploration_achievements", "200" ),
            new Tuple<string, string>( "Exploration_achievements", "250" ),
            new Tuple<string, string>( "Exploration_achievements", "300" ),
            new Tuple<string, string>( "Exploration_achievements", "350" ),
            new Tuple<string, string>( "Exploration_achievements", "400" ),
            new Tuple<string, string>( "Caving_Into_the_Gains", "Caving Into the Gains - Woodcutting" ),
            new Tuple<string, string>( "Caving_Into_the_Gains", "Caving Into the Gains - Agility" ),
            new Tuple<string, string>( "Caving_Into_the_Gains", "Caving Into the Gains - Crafting" ),
            new Tuple<string, string>( "Caving_Into_the_Gains", "Caving Into the Gains - Coins" ),
            new Tuple<string, string>( "Chivalry_is_Dead", "Chivalry is Dead - Runes" ),
            new Tuple<string, string>( "Chivalry_is_Dead", "Chivalry is Dead - Ancient Combat Lamp" ),
            new Tuple<string, string>( "Chivalry_is_Dead", "Chivalry is Dead - Gilded Cabbage" ),
            new Tuple<string, string>( "Chivalry_is_Dead", "Chivalry is Dead - Ancient Prayer Lamp" ),
            new Tuple<string, string>( "Chivalry_Is_Fed", "Chivalry is Fed" ),
            new Tuple<string, string>( "Chivalry_Is_Threads", "Chivalry is Threads" ),
            new Tuple<string, string>( "Brothers_Gower", "Brothers Gower - Ian" ),
            new Tuple<string, string>( "Brothers_Gower", "Brothers Gower - Paul" ),
            new Tuple<string, string>( "Brothers_Gower", "Brothers Gower - Andrew" ),
            new Tuple<string, string>( "Tasty_Bobbles", "Tasty Bobbles" ),


            //Text
            new Tuple<string, string>( "Diaries_of_the_Clans", "Diaries of the Clans" ),
            new Tuple<string, string>( "Diary_of_Oreb", "Diary of Oreb" ),
            new Tuple<string, string>( "Diary_of_the_Gods", "Diary of the Gods" ),
            new Tuple<string, string>( "Do_a_Minion,_Take_Notes", "Do a Minion, Take Notes" ),
            new Tuple<string, string>( "Don%27t_Fear_the_Ripper", "Don't Fear the Ripper" ),
            new Tuple<string, string>( "Dragonkin_Logs", "Dragonkin Logs" ),
            new Tuple<string, string>( "Forcae%27s_Mettle", "Forcae's Mettle" ),
            new Tuple<string, string>( "Exploration_achievements", "Kaigi" ),
            new Tuple<string, string>( "Exploration_achievements", "Ughtanatos" ),
            new Tuple<string, string>( "Exploration_achievements", "Horror" ),
            new Tuple<string, string>( "Exploration_achievements", "Qbd Journals" ),
            new Tuple<string, string>( "Exploration_achievements", "Tarddian" ),
            new Tuple<string, string>( "Grondabans%27_legacy", "Grondabans' legacy" ),
            new Tuple<string, string>( "Exploration_achievements", "Last Riders Book" ),
            new Tuple<string, string>( "Explore_for_Nestor", "Explore for Nestor" ),
            new Tuple<string, string>( "Nex", "The Praesul" ),
            new Tuple<string, string>( "Nex", "The Promised Gift" ),
            new Tuple<string, string>( "Behemoth_Notes_(achievement)", "Behemoth Notes" ),
            new Tuple<string, string>( "History_of_Bilrach", "History of Bilrach" ),
            new Tuple<string, string>( "Dragon_Ink", "Dragon Ink" ),


            //Various
            new Tuple<string, string>( "Angs_off_my_Ring", "Angs off my Ring" ),
            new Tuple<string, string>( "Annihilator", "Annihilator" ),
            new Tuple<string, string>( "Arise_from_the_Ash", "Arise from the Ash" ),
            new Tuple<string, string>( "Enough_of_the_Crazy_Walking", "Enough of the Crazy Walking" ),
            new Tuple<string, string>( "Got_a_Vyre_Reputation", "Got a Vyre Reputation" ),
            new Tuple<string, string>( "Complete_Trekky", "Complete Trekky" ),
            new Tuple<string, string>( "I%27m_Forever_Washing_Shadows", "I'm Forever Washing Shadows" ),
            new Tuple<string, string>( "Exploration_achievements", "Rush of Blood" ),
            new Tuple<string, string>( "Exploration_achievements", "30 Chompy Birds" ),
            new Tuple<string, string>( "Exploration_achievements", "Tooth Creature Pet" ),
            new Tuple<string, string>( "Exploration_achievements", "History of the Order" ),
            new Tuple<string, string>( "Otto_the_Ancient", "Otto the Ancient" ),
            new Tuple<string, string>( "Exploration_achievements", "Dimension of Disaster Rewards" ),
            new Tuple<string, string>( "Exploration_achievements", "Enhanced Fire Cape" ),
            new Tuple<string, string>( "Exploration_achievements", "Master White Knight" ),
            new Tuple<string, string>( "Exploration_achievements", "Demon Statuettes" ),
            new Tuple<string, string>( "Goebie_Relics", "Goebie Relics" ),
            new Tuple<string, string>( "Hau_Comes_to_Templeton", "Haul Comes to Templeton" ),
            new Tuple<string, string>( "Herbi%27s_Flax", "Herbi's Flax" ),
            new Tuple<string, string>( "I_Dig_This_Transportation", "I Dig This Transportation" ),
            new Tuple<string, string>( "I_know,_I_was_there...", "I know, I was there..." ),
            new Tuple<string, string>( "Ice_Ice_Chimpy", "Ice Ice Chimpy" ),
            new Tuple<string, string>( "Exploration_achievements", "Full Kudos obtained" ),
            new Tuple<string, string>( "Exploration_achievements", "Epic of Bukalla seen" ),
            new Tuple<string, string>( "Exploration_achievements", "Dorgesh-kaan Food Trading" ),
            new Tuple<string, string>( "Exploration_achievements", "Razmire and Ulsquire cured" ),
            new Tuple<string, string>( "Exploration_achievements", "Ourania Teleport unlocked" ),
            new Tuple<string, string>( "Exploration_achievements", "Wilderness Rogue Trader" ),
            new Tuple<string, string>( "Exploration_achievements", "Seren Memoriam Crystals" ),
            new Tuple<string, string>( "Exploration_achievements", "Prifddinas Memoriam Crystals" ),
            new Tuple<string, string>( "Exploration_achievements", "Zarosian Memoriam Crystals" ),
            new Tuple<string, string>( "Exploration_achievements", "Helmet of Trials" ),
            new Tuple<string, string>( "As_Taxed_as_a_Yak", "As Taxed as a Yak" ),
            new Tuple<string, string>( "Bandos%27s_Memories_(achievement)", "Bandos's Memories" ),
            new Tuple<string, string>( "Bane_Tuner", "Bane Tuner" ),
            new Tuple<string, string>( "Brutal_Stuffsies", "Brutal Stuffsies" ),
            new Tuple<string, string>( "Cecilia,_I%27m_Begging_You,_Please...", "Cecilia, I'm Begging you, Please" ),
            new Tuple<string, string>( "Challenging_Chat", "Challenging Chat" ),
            new Tuple<string, string>( "Chilling_with_Arrav", "Chilling with Arrav" ),
            new Tuple<string, string>( "Clue%27s_in_the_Monkey_Drool", "Clue's in the Monkey Drool" ),
            new Tuple<string, string>( "Complete_History_of_Droalak", "Complete History of Droalak" ),
            new Tuple<string, string>( "Daemonology_of_Celerity", "Daemonology of Celerity" ),
            new Tuple<string, string>( "Death_to_the_Mahjarrat", "Death to the Mahjarrat" ),
            new Tuple<string, string>( "For_the_Love_of_Mabel", "For the Love of Mabel" ),
            new Tuple<string, string>( "Exploration_achievements", "Ivandis Flail 500" ),
            new Tuple<string, string>( "Bridge_over_Fremmy_Waters", "Bridge over Fremmy Waters" ),
            new Tuple<string, string>( "Exploration_achievements", "Potion Recipes" ),
            new Tuple<string, string>( "Exploration_achievements", "Vicendithas' Scribblings" ),
            new Tuple<string, string>( "All_Rise", "All Rise - 4 Court Cases" ),
            new Tuple<string, string>( "All_Rise", "All Rise - 8 Court Cases" ),
            new Tuple<string, string>( "All_Rise", "All Rise - 12 Court Cases" ),
            new Tuple<string, string>( "All_Rise", "All Rise - 16 Court Cases" ),
            new Tuple<string, string>( "Dishonourable_Gains", "Dishonourable Gains - 50" ),
            new Tuple<string, string>( "Dishonourable_Gains", "Dishonourable Gains - 70" ),
            new Tuple<string, string>( "Dishonourable_Gains", "Dishonourable Gains - 90" ),
            new Tuple<string, string>( "Dishonourable_Loot", "Dishonourable Loot" ),
        
            
            //Areas/Activities
            new Tuple<string, string>( "Distorted_Div", "Distorted Div" ),
            new Tuple<string, string>( "Dusting_Murial", "Dusting Murial" ),
            new Tuple<string, string>( "Family_Spirit_Tree", "Family Spirit Tree" ),
            new Tuple<string, string>( "Fires_Are_Mostly_Harmless", "Fires Are Mostly Harmless - Mos Le'Harmless" ),
            new Tuple<string, string>( "Guthix_and_the_Chamber_of_Secrets", "Guthix and the Chamber of Secrets - Aagi" ),
            new Tuple<string, string>( "Guthix_and_the_Chamber_of_Secrets", "Guthix and the Chamber of Secrets - Seren" ),
            new Tuple<string, string>( "Guthix_and_the_Chamber_of_Secrets", "Guthix and the Chamber of Secrets - Aagi" ),
            new Tuple<string, string>( "Guthix_and_the_Chamber_of_Secrets", "Guthix and the Chamber of Secrets - Edicts" ),
            new Tuple<string, string>( "Guthix_and_the_Chamber_of_Secrets", "Guthix and the Chamber of Secrets - Cres" ),
            new Tuple<string, string>( "I_Can_See_For_Miles_and_Miles", "I Can See For Miles and Miles - 1 -&gt; 6" ),
            new Tuple<string, string>( "I_Can_See_For_Miles_and_Miles", "I Can See For Miles and Miles - 7 -&gt; 10" ),
            new Tuple<string, string>( "I_Can_See_For_Miles_and_Miles", "I Can See For Miles and Miles - 11 -&gt; 14" ),
            new Tuple<string, string>( "Impressing_Char", "Impressing Char" ),
            new Tuple<string, string>( "Exploration_achievements", "Jewel Memories" ),
            new Tuple<string, string>( "Exploration_achievements", "Pig Creation Machine (84)" ),
            new Tuple<string, string>( "Exploration_achievements", "Elder God Chronicles" ),
            new Tuple<string, string>( "Exploration_achievements", "Overgrown Idols" ),
            new Tuple<string, string>( "Exploration_achievements", "Memorial to Guthix Engrams" ),
            new Tuple<string, string>( "Exploration_achievements", "Senntisten Digsite Letters" ),
            new Tuple<string, string>( "Exploration_achievements", "Crystal Singing Research" ),
            new Tuple<string, string>( "Exploration_achievements", "Removing Corruption" ),
            new Tuple<string, string>( "Exploration_achievements", "Barbarian Training" ),
            new Tuple<string, string>( "Azdaran_Birthright", "Azdaran Birthright - Statue 1" ),
            new Tuple<string, string>( "Azdaran_Birthright", "Azdaran Birthright - Statue 2" ),
            new Tuple<string, string>( "Azdaran_Birthright", "Azdaran Birthright - Statue 3" ),
            new Tuple<string, string>( "Azdaran_Birthright", "Azdaran Birthright - Statue 4" ),
            new Tuple<string, string>( "Azdaran_Birthright", "Azdaran Birthright - Statue 5" ),
            new Tuple<string, string>( "Azdaran_Birthright", "Azdaran Birthright - Statue 6" ),
            new Tuple<string, string>( "Azdaran_Birthright", "Azdaran Birthright - Statue 7" ),
            new Tuple<string, string>( "Azdaran_Birthright", "Azdaran Birthright - Statue 8" ),
            new Tuple<string, string>( "Azdaran_Birthright", "Azdaran Birthright - Statue 9" ),
            new Tuple<string, string>( "Azdaran_Birthright", "Azdaran Birthright - Statue 10" ),
            new Tuple<string, string>( "Exploration_achievements", "Ancient Cavern Fairy Ring" ),
            new Tuple<string, string>( "Exploration_achievements", "King Roald Inferno Adze" ),
            new Tuple<string, string>( "Exploration_achievements", "Ornate Bowl" ),
            new Tuple<string, string>( "Exploration_achievements", "Giant Oyster" ),
            new Tuple<string, string>( "Exploration_achievements", "3 Spirit Trees" ),
            new Tuple<string, string>( "Exploration_achievements", "Re-Kindle Dragon Forge" ),
            new Tuple<string, string>( "Eeeeagle!", "Eeeeagle!" ),
            new Tuple<string, string>( "Exploration_achievements", "Elder Chronicles" ),
            new Tuple<string, string>( "Exploration_achievements", "Sunken Temple Murals" ),
            new Tuple<string, string>( "Ape_A%27hollow", "Ape A'hollow" ),
            new Tuple<string, string>( "Are_You_Needing_Access%3F", "Are You Needing Access?" ),
            new Tuple<string, string>( "As_clear_as_a_Crystal_Seed", "As clear as a Crystal Seed" ),
            new Tuple<string, string>( "Cran_Door%27s_Secret", "Cran Door's Secret" ),
            new Tuple<string, string>( "Here_Was_a_Scabaras_Mask", "Here Was a Scabaras Mask" ),
            new Tuple<string, string>( "Exploration_achievements", "Our Man in the North - Treasure Room" ),
            new Tuple<string, string>( "Exploration_achievements", "Crocodile Tears - Treasure Room" ),
            new Tuple<string, string>( "Exploration_achievements", "Missing My Mummy - Shortcut" ),
            new Tuple<string, string>( "Exploration_achievements", "Varrock Museum - Kudos" ),
        

                
            //God Emissary
            new Tuple<string, string>( "Exploration_achievements", "Goblins" ),
            new Tuple<string, string>( "Exploration_achievements", "Knights" ),
            new Tuple<string, string>( "Exploration_achievements", "Soldiers" ),
            new Tuple<string, string>( "Exploration_achievements", "Kalphite" ),
            new Tuple<string, string>( "Exploration_achievements", "Items" ),
            new Tuple<string, string>( "Exploration_achievements", "Artifact" ),
            new Tuple<string, string>( "Exploration_achievements", "Eggs/Swords" ),
            new Tuple<string, string>( "Exploration_achievements", "Fragments" ),
            new Tuple<string, string>( "Exploration_achievements", "Logs/Cloth" ),
            new Tuple<string, string>( "Exploration_achievements", "Thieve/Hunt" ),
            new Tuple<string, string>( "Exploration_achievements", "Artifact" ),
            new Tuple<string, string>( "Exploration_achievements", "Armour" ),
            new Tuple<string, string>( "Exploration_achievements", "Fragments" ),
            new Tuple<string, string>( "Exploration_achievements", "Altars" ),
            new Tuple<string, string>( "Exploration_achievements", "Artifact" ),

        };

        public List<Tuple<string, string>> CheckBoxTupleInfoComp = new List<Tuple<string, string>>
        {
            //Miniquests
            new Tuple<string, string>( "Abyssal_Reach", "The Abyss" ),
            new Tuple<string, string>( "Exploration_achievements", "Mahjarrat Memories" ),
            new Tuple<string, string>( "Exploration_achievements", "The Lost Toys" ),
            new Tuple<string, string>( "Exploration_achievements", "In Memory of the Myreque" ),
            new Tuple<string, string>( "Exploration_achievements", "Hopespear's Will" ),
            new Tuple<string, string>( "Exploration_achievements", "Returning Clarence" ),
            new Tuple<string, string>( "Exploration_achievements", "Knight Waves Training Grounds" ),
            new Tuple<string, string>( "Exploration_achievements", "The Lair of Tarn Razorlor" ),
            new Tuple<string, string>( "Desert-ed_Ghosts", "The Curse of Zaros" ),
            new Tuple<string, string>( "Exploration_achievements", "Stronghold of Player Safety" ),
            new Tuple<string, string>( "Exploration_achievements", "Stronghold of Security" ),


            //Tasks
            new Tuple<string, string>( "Exploration_achievements", "Ardougne" ),
            new Tuple<string, string>( "Exploration_achievements", "Desert" ),
            new Tuple<string, string>( "Exploration_achievements", "Daemonheim" ),
            new Tuple<string, string>( "Exploration_achievements", "Falador" ),
            new Tuple<string, string>( "Exploration_achievements", "Fremennik" ),
            new Tuple<string, string>( "Exploration_achievements", "Karamja" ),
            new Tuple<string, string>( "Exploration_achievements", "Lumbridge" ),
            new Tuple<string, string>( "Exploration_achievements", "Morytania" ),
            new Tuple<string, string>( "Exploration_achievements", "Seers' village" ),
            new Tuple<string, string>( "Exploration_achievements", "Tirannwn" ),
            new Tuple<string, string>( "Exploration_achievements", "Varrock" ),
            new Tuple<string, string>( "Exploration_achievements", "Wilderness" ),
            new Tuple<string, string>( "Exploration_achievements", "Ardougne" ),
            new Tuple<string, string>( "Exploration_achievements", "Desert" ),
            new Tuple<string, string>( "Exploration_achievements", "Daemonheim" ),
            new Tuple<string, string>( "Exploration_achievements", "Falador" ),
            new Tuple<string, string>( "Exploration_achievements", "Fremennik" ),
            new Tuple<string, string>( "Exploration_achievements", "Karamja" ),
            new Tuple<string, string>( "Exploration_achievements", "Lumbridge" ),
            new Tuple<string, string>( "Exploration_achievements", "Morytania" ),
            new Tuple<string, string>( "Exploration_achievements", "Seers' village" ),
            new Tuple<string, string>( "Exploration_achievements", "Tirannwn" ),
            new Tuple<string, string>( "Exploration_achievements", "Varrock" ),
            new Tuple<string, string>( "Exploration_achievements", "Wilderness" ),
            new Tuple<string, string>( "Exploration_achievements", "Ardougne" ),
            new Tuple<string, string>( "Exploration_achievements", "Desert" ),
            new Tuple<string, string>( "Exploration_achievements", "Daemonheim" ),
            new Tuple<string, string>( "Exploration_achievements", "Falador" ),
            new Tuple<string, string>( "Exploration_achievements", "Fremennik" ),
            new Tuple<string, string>( "Exploration_achievements", "Karamja" ),
            new Tuple<string, string>( "Exploration_achievements", "Lumbridge" ),
            new Tuple<string, string>( "Exploration_achievements", "Morytania" ),
            new Tuple<string, string>( "Exploration_achievements", "Seers' village" ),
            new Tuple<string, string>( "Exploration_achievements", "Tirannwn" ),
            new Tuple<string, string>( "Exploration_achievements", "Varrock" ),
            new Tuple<string, string>( "Exploration_achievements", "Wilderness" ),
            new Tuple<string, string>( "Exploration_achievements", "Ardougne" ),
            new Tuple<string, string>( "Exploration_achievements", "Desert" ),
            new Tuple<string, string>( "Exploration_achievements", "Daemonheim" ),
            new Tuple<string, string>( "Exploration_achievements", "Falador" ),
            new Tuple<string, string>( "Exploration_achievements", "Fremennik" ),
            new Tuple<string, string>( "Exploration_achievements", "Karamja" ),
            new Tuple<string, string>( "Exploration_achievements", "Morytania" ),
            new Tuple<string, string>( "Exploration_achievements", "Seers' village" ),
            new Tuple<string, string>( "Exploration_achievements", "Tirannwn" ),
            new Tuple<string, string>( "Exploration_achievements", "Varrock" ),
            new Tuple<string, string>( "Exploration_achievements", "Wilderness" ),
            new Tuple<string, string>( "Exploration_achievements", "Pyramid Scheme" ),
            new Tuple<string, string>( "Exploration_achievements", "Lumbridge Beginner" ),
        
            
            //Skilling            
            new Tuple<string, string>( "Almost_as_Perky_as_a_Prawn", "Almost as Perky as a Prawn" ),
            new Tuple<string, string>( "Big_Chinchompa_(achievement)", "Big Chinchompa" ),
            new Tuple<string, string>( "Deadlier_Catch", "Deadler Catch" ),
            new Tuple<string, string>( "Diaries_of_the_Clans", "Diaries of the Clans" ),
            new Tuple<string, string>( "Family_Spirit_Tree", "Family Spirit Tree" ),
            new Tuple<string, string>( "Data_Recovery", "Data Recovery - Aagi" ),
            new Tuple<string, string>( "Data_Recovery", "Data Recovery - Seren" ),
            new Tuple<string, string>( "Data_Recovery", "Data Recovery - Juna" ),
            new Tuple<string, string>( "Data_Recovery", "Data Recovery - Edicts" ),
            new Tuple<string, string>( "Data_Recovery", "Data Recovery - Cres" ),
            new Tuple<string, string>( "Imping_Around", "Imping Around" ),
            new Tuple<string, string>( "Invention_Gives_Me_the_Blues", "Invention Gives Me the Blues" ),
            new Tuple<string, string>( "Exploration_achievements", "Full Kudos Obtained" ),
            new Tuple<string, string>( "Exploration_achievements", "Memorial To Guthix Prestige 1" ),
            new Tuple<string, string>( "Exploration_achievements", "Crystal Singing Research" ),
            new Tuple<string, string>( "Exploration_achievements", "Removing Corruption" ),
            new Tuple<string, string>( "Exploration_achievements", "Full Yaktwee Stick" ),
            new Tuple<string, string>( "Exploration_achievements", "POP Tutorial" ),
            new Tuple<string, string>( "Exploration_achievements", "First Statue of Rhiannon" ),
            new Tuple<string, string>( "Doric_and_Boric_tasks#Doric's_tasks", "Doric's first" ),
            new Tuple<string, string>( "Doric_and_Boric_tasks#Doric's_tasks", "Doric's second" ),
            new Tuple<string, string>( "Doric_and_Boric_tasks#Doric's_tasks", "Doric's third" ),
            new Tuple<string, string>( "Doric_and_Boric_tasks#Doric's_tasks", "Doric's fourth" ),
            new Tuple<string, string>( "Doric_and_Boric_tasks#Doric's_tasks", "Doric's fifth" ),
            new Tuple<string, string>( "Doric_and_Boric_tasks#Doric's_tasks", "Doric's sixth" ),
            new Tuple<string, string>( "Doric_and_Boric_tasks#Doric's_tasks", "Doric's seventh" ),
            new Tuple<string, string>( "Doric_and_Boric_tasks#Doric's_tasks", "Doric's eighth" ),
            new Tuple<string, string>( "Doric_and_Boric_tasks#Boric's_tasks_(m)", "Boric's first" ),
            new Tuple<string, string>( "Doric_and_Boric_tasks#Boric's_tasks_(m)", "Boric's second" ),
            new Tuple<string, string>( "Doric_and_Boric_tasks#Boric's_tasks_(m)", "Boric's third" ),
            new Tuple<string, string>( "Elven_Titles", "Of the Trahaearn" ),
            new Tuple<string, string>( "Elven_Titles", "Of the Crwys" ),
            new Tuple<string, string>( "Elven_Titles", "Of the Amlodd" ),
            new Tuple<string, string>( "Elven_Titles", "Of the Ithell" ),
            new Tuple<string, string>( "Elven_Titles", "Of the Hefin" ),
            new Tuple<string, string>( "Elven_Titles", "Of the Meilyr" ),


            //Combat
            new Tuple<string, string>( "Exploration_achievements", "Annihilator" ),
            new Tuple<string, string>( "Bipedal_Mask", "Bipedal Mask" ),
            new Tuple<string, string>( "Bridge_over_Fremmy_Waters", "Bridge over Fremmy Waters" ),
            new Tuple<string, string>( "I%27m_Forever_Washing_Shadows", "I'm Forever Washing Shadows" ),
            new Tuple<string, string>( "Exploration_achievements", "Fight Kiln" ),
            new Tuple<string, string>( "Exploration_achievements", "Queen Black Dragon" ),
            new Tuple<string, string>( "Exploration_achievements", "Qbd First Journal" ),
            new Tuple<string, string>( "Exploration_achievements", "Rush of Blood" ),
            new Tuple<string, string>( "Exploration_achievements", "Potion Recipes" ),
            new Tuple<string, string>( "Famous_(achievement)", "Famous" ),
            new Tuple<string, string>( "Slayer_Master_(achievement)", "Slayer Master" ),
            new Tuple<string, string>( "Heal,_Quickly", "Heal, Quickly" ),
            new Tuple<string, string>( "Elven_Titles", "Of the Iorwerth" ),
            new Tuple<string, string>( "Elven_Titles", "Of the Cadarn" ),


            //Etc.
            new Tuple<string, string>( "Bandos%27s_Memories_(achievement)", "Bandos's Memoreis" ),
            new Tuple<string, string>( "Bane_Tuner", "Bane Tuner" ),
            new Tuple<string, string>( "Claus_Is_Rising", "Claus Is Rising" ),
            new Tuple<string, string>( "Exploration_achievements", "Ourania Teleport" ),
            new Tuple<string, string>( "Exploration_achievements", "Seren Memoriam Crystals" ),
            new Tuple<string, string>( "Exploration_achievements", "Prifddinas Memoriam Crystals" ),
            new Tuple<string, string>( "Exploration_achievements", "Zarosian Memoriam Crystals" ),
        };

        public List<Tuple<string, string>> CheckBoxTupleInfoTrim = new List<Tuple<string, string>>
        {
            //Miniquests
            new Tuple<string, string>( "Exploration_achievements", "Barbarian Training" ),
            new Tuple<string, string>( "Banking_History", "Banking History" ),
            new Tuple<string, string>( "Exploration_achievements", "Tales of Nomad" ),
            new Tuple<string, string>( "Exploration_achievements", "Rogue Trader Rune Shop" ),
            new Tuple<string, string>( "Fred%27s_Shearings", "Sheep Shearer" ),
            new Tuple<string, string>( "Exploration_achievements", "Tales of the God Wars" ),
            new Tuple<string, string>( "Exploration_achievements", "Witch's Potion" ),
            new Tuple<string, string>( "From_Tiny_Acorns", "From Tiny Acorns" ),
            new Tuple<string, string>( "Lost_Her_Marbles", "Lost Her Marbles" ),
            new Tuple<string, string>( "A_Guild_of_Our_Own", "A Guild of Our Own" ),


            //Skilling
            new Tuple<string, string>( "Eeeeagle!", "Eeeeagle!" ),
            new Tuple<string, string>( "Impressing_Char", "Impressing Char" ),
            new Tuple<string, string>( "Perky_like_a_Prawn", "Perky like a Prawn" ),
            new Tuple<string, string>( "Exploration_achievements", "Song From The Depths" ),
            new Tuple<string, string>( "Exploration_achievements", "Elder Chronicles" ),
            new Tuple<string, string>( "Exploration_achievements", "Sober Up Skippy" ),
            new Tuple<string, string>( "Exploration_achievements", "Memorial To Guthix 4" ),
            new Tuple<string, string>( "Seagullible", "Seagullible" ),
            new Tuple<string, string>( "Class_Crown", "Class Crown" ),
            new Tuple<string, string>( "Lock,_Stock_and_Barrel", "Lock, Stock and Barrel" ),
            new Tuple<string, string>( "To_The_Bone", "To The Bone" ),
            new Tuple<string, string>( "Ice_Ice_Chimpy", "Ice Ice Chimpy" ),
            new Tuple<string, string>( "Agile_from_Head_to_Toe", "Agile from Head to Toe - Top" ),
            new Tuple<string, string>( "Agile_from_Head_to_Toe", "Agile from Head to Toe - Legs" ),
            new Tuple<string, string>( "Advanced_Sweeping", "Advanced Sweeping - The Apprentice" ),
            new Tuple<string, string>( "Advanced_Sweeping", "Advanced Sweeping - Ali the Hag" ),
            new Tuple<string, string>( "Advanced_Sweeping", "Advanced Sweeping - Old Crone" ),
            new Tuple<string, string>( "Advanced_Sweeping", "Advanced Sweeping - Baba Yaga" ),
            new Tuple<string, string>( "Advanced_Sweeping", "Advanced Sweeping - Kardia" ),
            new Tuple<string, string>( "Around_the_World_in_Six_Ways", "Around the World in Six Ways - Crafting Guild" ),
            new Tuple<string, string>( "Around_the_World_in_Six_Ways", "Around the World in Six Ways - Lumber Yard" ),
            new Tuple<string, string>( "Around_the_World_in_Six_Ways", "Around the World in Six Ways - Castle Wars" ),
            new Tuple<string, string>( "Around_the_World_in_Six_Ways", "Around the World in Six Ways - Grand Tree" ),


            //Combat
            new Tuple<string, string>( "Barbarian_Scavenger", "Barbarian Scavenger" ),
            new Tuple<string, string>( "Complete_Trekky", "Complete Trekky" ),
            new Tuple<string, string>( "Exploration_achievements", "Master White Knight" ),
            new Tuple<string, string>( "Finish_Him!", "Finish Him!" ),
            new Tuple<string, string>( "Hard_as_Daemons", "Hard as Daemons" ),
            new Tuple<string, string>( "Ivan_is_Flailing", "Ivan is Flailing" ),
            new Tuple<string, string>( "Exploration_achievements", "Battle Commendations" ),
            new Tuple<string, string>( "Maria,_You_Gotta_See_Her", "Maria, You Gotta See Her" ),
            new Tuple<string, string>( "Exploration_achievements", "Hardmode Nomad" ),
            new Tuple<string, string>( "Exploration_achievements", "Penance King" ),
            new Tuple<string, string>( "Exploration_achievements", "Qbd Journals" ),
            new Tuple<string, string>( "Exploration_achievements", "Scabarites Notes" ),
            new Tuple<string, string>( "Exploration_achievements", "Dungeoneering Scroll Traits" ),
            new Tuple<string, string>( "Exploration_achievements", "Survive ROTS" ),
            new Tuple<string, string>( "Exploration_achievements", "Telos 100%" ),
            new Tuple<string, string>( "Exploration_achievements", "Mazcab Teleport Spell" ),
            new Tuple<string, string>( "Conquest_Adore", "Conquest Adore" ),
            new Tuple<string, string>( "Death_Effect", "Death Effect" ),
            new Tuple<string, string>( "Exploration_achievements", "Desert Slayer Dungeon" ),
            new Tuple<string, string>( "Exploration_achievements", "All Slayer Items" ),
            new Tuple<string, string>( "Exploration_achievements", "Slayer Codex" ),
            new Tuple<string, string>( "Ferocious_Upgrade", "Ferocious Upgrade" ),


            //Progressions
            new Tuple<string, string>( "All_Rise", "All Rise - 4 Court Cases" ),
            new Tuple<string, string>( "All_Rise", "All Rise - 8 Court Cases" ),
            new Tuple<string, string>( "All_Rise", "All Rise - 12 Court Cases" ),
            new Tuple<string, string>( "All_Rise", "All Rise - 16 Court Cases" ),
            new Tuple<string, string>( "Champions,_What_Champions%3F", "Champions, What Champions? - 3 Scrolls" ),
            new Tuple<string, string>( "Champions,_What_Champions%3F", "Champions, What Champions? - 6 Scrolls" ),
            new Tuple<string, string>( "Champions,_What_Champions%3F", "Champions, What Champions? - 9 Scrolls" ),
            new Tuple<string, string>( "Champions,_What_Champions%3F", "Champions, What Champions? - 12 Scrolls" ),
            new Tuple<string, string>( "Champions,_What_Champions%3F", "Champions, What Champions? - 15 Scrolls" ),
            new Tuple<string, string>( "Chompy_Massacre", "Chompy Massacre - 30" ),
            new Tuple<string, string>( "Chompy_Massacre", "Chompy Massacre - 130" ),
            new Tuple<string, string>( "Chompy_Massacre", "Chompy Massacre - 300" ),
            new Tuple<string, string>( "Chompy_Massacre", "Chompy Massacre - 500" ),
            new Tuple<string, string>( "Chompy_Massacre", "Chompy Massacre - 700" ),
            new Tuple<string, string>( "Chompy_Massacre", "Chompy Massacre - 1000" ),
            new Tuple<string, string>( "Chompy_Massacre", "Chompy Massacre - 1500" ),
            new Tuple<string, string>( "Chompy_Massacre", "Chompy Massacre - 2250" ),
            new Tuple<string, string>( "Chompy_Massacre", "Chompy Massacre - 3250" ),
            new Tuple<string, string>( "Chompy_Massacre", "Chompy Massacre - 4000" ),


            //Castle Wars
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 50" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 100" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 150" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 200" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 250" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 300" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 350" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 400" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 450" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 500" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 550" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 600" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 650" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 700" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 750" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 800" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 850" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 900" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 950" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 1000" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 1050" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 1100" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 1150" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 1200" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 1250" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 1300" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 1350" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 1400" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 1450" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 1500" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 1550" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 1600" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 1650" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 1700" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 1750" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 1800" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 1850" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 1900" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 1950" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 2000" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 2050" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 2100" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 2150" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 2200" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 2250" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 2300" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 2350" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 2400" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 2450" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 2500" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 2550" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 2600" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 2650" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 2700" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 2750" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 2800" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 2850" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 2900" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 2950" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 3000" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 3050" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 3100" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 3150" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 3200" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 3250" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 3300" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 3350" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 3400" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 3450" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 3500" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 3550" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 3600" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 3650" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 3700" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 3750" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 3800" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games? - 4000" ),
            new Tuple<string, string>( "How_Many_Games%3F", "How Many Games?" ),
        };

        public List<Tuple<string, string>> CheckBoxTupleInfoSalty = new List<Tuple<string, string>>
        {
            new Tuple<string, string>( "Arc_-_Upgrading_Waiko", "Upgrading Waiko" ),
            new Tuple<string, string>( "Arc_-_Unlocking_Waiko", "Unlocking Waiko" ),
            new Tuple<string, string>( "Arc_-_Ancient_Eastern_Tortle_Portals", "Ancient Eastern Tortle Portals" ),
            new Tuple<string, string>( "Arc_-_All_Your_Energies", "All Your Energies" ),
            new Tuple<string, string>( "Arc_-_Don%27t_Crush_my_Memories", "Don't Crush my Memories" ),
            new Tuple<string, string>( "Arc_-_Bone_To_Pick_With_You", "Bone To Pick With You" ),
            new Tuple<string, string>( "Arc_-_Mitts_and_Waders_-_Death_Lotus", "Mitts and Waders - Death Lotus" ),
            new Tuple<string, string>( "Exploration_achievements", "Death Lotus Outfit" ),
            new Tuple<string, string>( "Arc_-_Mitts_and_Waders_-_Seasinger", "Mitts and Waders - Seasinger" ),
            new Tuple<string, string>( "Exploration_achievements", "Seasinger Outfit" ),
            new Tuple<string, string>( "Arc_-_Mitts_and_Waders_-_Tetsu", "Mitts and Waders - Tetsu" ),
            new Tuple<string, string>( "Exploration_achievements", "Tetsu Outfit" ),
            new Tuple<string, string>( "Arc_I_-_Flag_Fall", "Flag Fall" ),
            new Tuple<string, string>( "Arc_II_-_Head_of_the_Family", "Head of the Family" ),
            new Tuple<string, string>( "Arc_III_-_Spiritual_Enlightenment", "Spiritual Enlightenment" ),
            new Tuple<string, string>( "Arc_IV_-_Jed_Hunter", "Jed Hunter" ),
            new Tuple<string, string>( "Arc_V_-_Eye_for_an_Eye", "Eye for an Eye" ),
            new Tuple<string, string>( "Arc_VI_-_Harbinger_of_Doom", "Harbinger of Doom" ),
            new Tuple<string, string>( "Arc_VII_-_Tuai_Leit%27s_Own", "Tuai Leit's Own" ),
            new Tuple<string, string>( "Arc_VIII_-_Ghosts_from_the_Past", "Ghosts from the Past" ),
            new Tuple<string, string>( "Arc_IX_-_Damage_Control", "Damage Control" ),
            new Tuple<string, string>( "Arc_X_-_Final_Destination", "Final Destination" ),
        };

        public void LoadCheckBoxes()
		{
			string linkPrefix = "https://runescape.wiki/w/";

			AllCheckboxes = new ObservableCollection<CheckBoxModel>	
            {				
				new CheckBoxModel(CheckBoxType.SelectAll, CheckBoxType.Mqc)
			};

            //new List<List<Tuple<string, string>>> {CheckBoxTupleInfoMqc, CheckBoxTupleInfoComp, CheckBoxTupleInfoTrim, CheckBoxTupleInfoSalty}.ForEach(x =>
            //{
            //    x.ForEach(tuple =>
            //    {
                    
            //    });
            //});

            CheckBoxTupleInfoMqc.ForEach(tuple =>
            {
                AllCheckboxes.Add(new CheckBoxModel(linkPrefix + tuple.Item1, tuple.Item2, CheckBoxType.Mqc));
            });

            CheckBoxTupleInfoComp.ForEach(tuple =>
            {
                AllCheckboxes.Add(new CheckBoxModel(linkPrefix + tuple.Item1, tuple.Item2, CheckBoxType.Comp));
            });

            CheckBoxTupleInfoTrim.ForEach(tuple =>
            {
                AllCheckboxes.Add(new CheckBoxModel(linkPrefix + tuple.Item1, tuple.Item2, CheckBoxType.Trim));
            });

            CheckBoxTupleInfoSalty.ForEach(tuple =>
            {
                AllCheckboxes.Add(new CheckBoxModel(linkPrefix + tuple.Item1, tuple.Item2, CheckBoxType.Salty));
            });
        }
	}
}
